-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 17:18:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vigono
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vigono
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vigono` DEFAULT CHARACTER SET utf8 ;
USE `vigono` ;

-- -----------------------------------------------------
-- Table `vigono`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigono`.`plano` (
  `idPlano` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `duracao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigono`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigono`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `Cpf` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `plano_idPlano` INT,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_plano1_idx` (`plano_idPlano` ASC),
  CONSTRAINT `fk_cliente_plano1`
    FOREIGN KEY (`plano_idPlano`)
    REFERENCES `vigono`.`plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigono`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigono`.`carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(45) NOT NULL,
  `Fabricante` VARCHAR(60) NOT NULL,
  `Ano` INT(4) NOT NULL,
  `Preco` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idCarro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigono`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigono`.`locacao` (
  `idLocacao` INT NOT NULL AUTO_INCREMENT,
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `carro_idCarro` INT NOT NULL,
  PRIMARY KEY (`idLocacao`),
  INDEX `fk_locacao_cliente_idx` (`cliente_idCliente` ASC),
  INDEX `fk_locacao_carro1_idx` (`carro_idCarro` ASC),
  CONSTRAINT `fk_locacao_cliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `vigono`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_carro1`
    FOREIGN KEY (`carro_idCarro`)
    REFERENCES `vigono`.`carro` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
